### ISSUE TITLE
Machine translate does not work with Glotpress 3.0

### ISSUE THREAD

**Issue by c-schmitz** [toolstack/gp-machine-translate#4]
WHen I click the 'Machine translate' link I get the message that the text was successfully translated,
but the field for the translated text in the  page stay empty.
I am guess that the JS does not find the input field properly.

**Comment by c-schmitz** [comment]
I am using Google Translate, btw.

**Comment by toolstack** [comment]
Sorry it took so long to look at this, but I've fixed the issue, will be doing a release shortly.
